### ISSUE TITLE
UI update for Community and Resources Section 

### ISSUE THREAD

**Issue by PriyanshuRj** [xolentum/website#7]
The buttons in the Community and Resources Section are all of different sizes they will look good if all of them have the same size and also in the mobile display the buttons have no padding in x direction which make them look bad attaching image proof of the same.
![image](https://user-images.githubusercontent.com/76838551/193395280-86747c50-a814-45ff-b39c-b59718575dd7.png)

I want to resolve this issue as my contribution to hacktoberfest 2022 please assign this task to me.

**Comment by sn1f3rt** [comment]
Alright sure, waiting for your contribution.

**Comment by PriyanshuRj** [comment]
Please accept it as a submission to Hacktoberfest 2022
